# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa11e0fc4c2c5ce50112198c144e2353c96bb622bef53bd807255f23c173ed51f8c4e4845cce88f4ef8926db85a599f9c15a6f01661c0191eb7a09fcaba20460

test:
  secret_key_base: 4a94bad2d617fee664d8c57ebab30bd3bd043bdb0146556db4a0b03388f43b24213c3f92027561daf448564370323316392ecf39c5dee8e35f031096a075e71a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
